name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install uwsgi
      run: apt-get install -y python3-pip && pip3 install uWSGI
    - name: compile
      run: uwsgi --build-plugin escape_json.c
